export default [
    {
        id: 1,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me2.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 2,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 3,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me2.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 4,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 5,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me2.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 6,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 7,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me2.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
    {
        id: 8,
        name: "Alex Moldovan",
        position: "Full Stack Developer",
        company: "Fortech",
        imageUrl: "/static/images/speakers/me.jpg",
        twitter: "https://twitter.com/alexnmoldovan",
        github: "https://github.com/alexnm",
        site: "https://medium.com/@alexnm",
    },
];
